Create a 2D array (an array of arrays)

In [1]:
# Define arrays 
import numpy as np

data = [50,50,47,97,49,3,53,42,26,74,82,62,37,15,70,27,36,35,48,52,63,64]
grades = np.array(data)

study_hours = [10.0,11.5,9.0,16.0,9.25,1.0,11.5,9.0,8.5,14.5,15.5,
               13.75,9.0,8.0,15.5,8.0,9.0,6.0,10.0,12.0,12.5,12.0]

student_data = np.array([study_hours, grades])

student_data

array([[10.  , 11.5 ,  9.  , 16.  ,  9.25,  1.  , 11.5 ,  9.  ,  8.5 ,
        14.5 , 15.5 , 13.75,  9.  ,  8.  , 15.5 ,  8.  ,  9.  ,  6.  ,
        10.  , 12.  , 12.5 , 12.  ],
       [50.  , 50.  , 47.  , 97.  , 49.  ,  3.  , 53.  , 42.  , 26.  ,
        74.  , 82.  , 62.  , 37.  , 15.  , 70.  , 27.  , 36.  , 35.  ,
        48.  , 52.  , 63.  , 64.  ]])

Creating a DataFrame

In [2]:
import pandas as pd

df_students = pd.DataFrame({'Name': ['Dan', 'Joann', 'Pedro', 'Rosie', 'Ethan', 'Vicky', 'Frederic', 'Jimmie', 
                                     'Rhonda', 'Giovanni', 'Francesca', 'Rajab', 'Naiyana', 'Kian', 'Jenny',
                                     'Jakeem','Helena','Ismat','Anila','Skye','Daniel','Aisha'],
                            'StudyHours':student_data[0],
                            'Grade':student_data[1]})

df_students

         Name  StudyHours  Grade
0         Dan       10.00   50.0
1       Joann       11.50   50.0
2       Pedro        9.00   47.0
3       Rosie       16.00   97.0
4       Ethan        9.25   49.0
5       Vicky        1.00    3.0
6    Frederic       11.50   53.0
7      Jimmie        9.00   42.0
8      Rhonda        8.50   26.0
9    Giovanni       14.50   74.0
10  Francesca       15.50   82.0
11      Rajab       13.75   62.0
12    Naiyana        9.00   37.0
13       Kian        8.00   15.0
14      Jenny       15.50   70.0
15     Jakeem        8.00   27.0
16     Helena        9.00   36.0
17      Ismat        6.00   35.0
18      Anila       10.00   48.0
19       Skye       12.00   52.0
20     Daniel       12.50   63.0
21      Aisha       12.00   64.0

The .loc function in pandas is used to access a group of rows and columns by labels or a boolean array. It allows for label-based indexing and slicing of data within a DataFrame.

DataFrame.loc[row_label, column_label]

In [ ]:
# Get the data for index value 5
df_students.loc[5]

In [ ]:
# Get the rows with index values from 0 to 5
# here you find rows based on the index
df_students.loc[0:20]

The .iloc function in pandas is used for integer-location based indexing. Unlike .loc, which accesses rows and columns by their labels, .iloc works with the numerical positions (or indices) of the rows and columns.

In [6]:
# Get the rows with index values from 0 to 5
# gets rows 0-4
df_students.iloc[0:5]

    Name  StudyHours  Grade
0    Dan       10.00   50.0
1  Joann       11.50   50.0
2  Pedro        9.00   47.0
3  Rosie       16.00   97.0
4  Ethan        9.25   49.0

In [ ]:
# Get data in the first row of the df_students.iloc[0]

df_students.iloc[0,[1,2]]

In [ ]:
# df_students[df_students['Name']=='Aisha']
df_students.loc[df_students['Name']=='Aisha']
# df_students.query('Name=="Aisha"')
# df_students[df_students.Name == 'Aisha']

Inner join DataFrames along an axis

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])

df2 = pd.DataFrame({'B': ['B2', 'B3', 'B4', 'B5'],
                    'D': ['D2', 'D3', 'D4', 'D5'],
                    'F': ['F2', 'F3', 'F4', 'F5']},
                   index=[2, 3, 4, 5])

result = pd.concat([df1, df2], axis=1, join='inner')

print(result)

Remove duplicate rows from DataFrame based on all columns using drop_duplicates() method

In [ ]:
import pandas as pd

df = pd.DataFrame({
        'A': [1, 2, 1, 1, 3],
        'B': [5, 4, 5, 5, 5],
        'C': [9, 10, 9, 9, 8]})

df_no_duplicates = df.drop_duplicates()
print(f"Original DataFrame\n{df}\n")
print(f"DataFrame with no duplicates\n{df_no_duplicates}")

Iterate over cells in DataFrame using DataFrame.shape and For loop

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
	[[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9],
	[10, 11, 12]])

for i in range(df.shape[0]): #iterate over rows
    for j in range(df.shape[1]): #iterate over columns
        value = df.at[i, j] #get cell value
        print(value, end="\t")
    print()

In [ ]:
# Iterate over Cells in a DataFrame using iterrows() method
import pandas as pd
import numpy as np

df = pd.DataFrame(
	[[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9],
	[10, 11, 12]])

for rowIndex, row in df.iterrows(): #iterate over rows
    for columnIndex, value in row.items():
        print(value, end="\t")
    print()
# Convert DataFrame to numpy array
arr = df.to_numpy()
print('\nNumpy Array\n----------\n', arr)

In [ ]:
#Import the dataset and pandas
from sklearn import datasets
import pandas as pd
 
# Load the diabetes dataset and create a dataframe
diabetes = datasets.load_diabetes()
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
 
# Add the target variable to the dataframe
df['target'] = diabetes.target
 
# Print the first 5 rows of some variables
print(df[['age', 'sex', 'bmi', 'target']].head())

In [ ]:
corr = df[['age', 'sex', 'bmi', 'target']].corr()
print(corr)